// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihxvtltuqsnasxdkmbhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloeHZ0bHR1cXNuYXN4ZGttYmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTUwNjksImV4cCI6MjA2NTA5MTA2OX0.Cs9JlS9IAMv5CkFN90Emaqd9NxG_tvNRK2c8FHJ2IVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});